-- 003_seed_cases.sql
-- Initial seed from old hardcoded src/data/cases.ts.

insert into public.cases (
  slug, agency_name, segment, published, sort_order,
  title, description, logo_url, avatar_url,
  subtitle, badge_label,
  challenge_heading, challenge_content,
  solution_heading, solution_content,
  results_heading, results_content,
  quote_text, quote_author_name, quote_author_role, quote_author_avatar_url,
  quote_cta_label, quote_cta_url,
  final_cta_heading, final_cta_body, final_cta_label, final_cta_url,
  metrics
) values
(
  'roi-lab',
  'ROI Lab Digital',
  'Marketing',
  true,
  1,
  'ROI Lab Digital: R$ 236.000 de Economia Anual com IA',
  'Como o ROI Lab Digital utilizou Inteligência Artificial para escalar operações e otimizar rotinas que antes consumiam horas da equipe.',
  'https://img.usecurling.com/i?q=roi+lab&shape=outline&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
  'Como a ROI Lab Digital estruturou a operação com IA, escalou o faturamento e preservou a margem sem inflar o time.',
  'Consultoria',
  'Crescimento travado pelo custo de pessoal.',
  '<p>A ROI Lab Digital, consultoria especializada em Outsourcing de Marketing e Vendas B2B, enfrentava um desafio crescente: a expansão dos negócios vinha acompanhada de um aumento proporcional nos custos com pessoal.</p>',
  'IA como pilar da operação.',
  '<p>A empresa implementou IA para otimizar a operação, começando por Tesouraria/BPO, automatizando processos financeiros e reduzindo a dependência de recursos humanos.</p>',
  'Economia comprovada e margem preservada.',
  '<p>A implementação da IA gerou <strong>R$ 236.000</strong> de economia anual e permitiu absorver novos contratos sem novas contratações.</p>',
  'A implementação da IA foi um divisor de águas. Conseguimos expandir nossa capacidade operacional e absorver novos grandes contratos sem comprometer a estrutura de custos.',
  'Matheus Gonzaga',
  'Founder · ROI Lab Digital',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=1',
  'Visitar ROI Lab Digital',
  'https://roilab.digital',
  'Sua agência vai ser o próximo case?',
  'Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.',
  'Aplicar agora',
  '#',
  '[{"value":"R$ 236.000","label":"Economia Gerada"},{"value":"3","label":"Contratações Evitadas"},{"value":"R$ 200.000","label":"Economia com pessoal"}]'::jsonb
),
(
  'orion','ORION','Tecnologia',true,2,
  'ORION: R$ 1 Milhão/Ano em Economia com Internalização',
  'Como a ORION utilizou o desenvolvimento interno para consolidar processos e ferramentas, garantindo autonomia e economia.',
  'https://img.usecurling.com/i?q=orion&shape=outline&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=2',
  'Case de eficiência operacional com IA.',
  'Tecnologia',
  'Estrutura externa cara e pouco escalável.',
  '<p>Contexto inicial do case ORION.</p>',
  'Internalização orientada por dados.',
  '<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Eficiência e autonomia operacional.',
  '<p>Resultados consolidados com redução de custo e ganho de velocidade.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"R$ 1 Milhão/Ano","label":"Economia Gerada"},{"value":"100%","label":"Operacional"}]'::jsonb
),
(
  'vize','Vize Imagem Masculina','Varejo',true,3,
  'Vize Imagem Masculina: Inovação com IA para escala',
  'Como Vize Imagem Masculina inteligência artificial usada para automatizar processos e melhorar o faturamento mensal.',
  null,
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=3',
  'Case de automação com ganho de produtividade.','Varejo',
  'Operação com gargalos de execução.','<p>Contexto inicial do case Vize.</p>',
  'Automação em processos-chave.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Mais eficiência e crescimento.','<p>Resultados consolidados com ganho de produtividade.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"Economia de Custos","label":"Potencial apenas"},{"value":"Maior Faturamento","label":"Aumento previsto"}]'::jsonb
),
(
  'map','MAP','Tecnologia',true,4,
  'MAP: Autonomia tecnológica e custos reduzidos com IA',
  'Como a MAP inteligência investida artificial para otimizar processos operacionais e eliminar custos recorrentes com software.',
  'https://img.usecurling.com/i?q=map&shape=fill&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=4',
  'Case de autonomia tecnológica.','Tecnologia',
  'Dependência de ferramentas caras.','<p>Contexto inicial do case MAP.</p>',
  'Arquitetura com IA aplicada.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Autonomia e redução de custo.','<p>Resultados consolidados de economia e controle operacional.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"Autonomia Total","label":"Operacional"},{"value":"Redução","label":"Custos com Ferramentas"}]'::jsonb
),
(
  'cpto','CPTO Connect','RH',true,5,
  'CPTO Connect: R$ 2.500 de economia mensal com IA no RH',
  'Como a CPTO Connect utilizou Inteligência Artificial para otimizar o setor de RH e ganhar agilidade nas contratações.',
  'https://img.usecurling.com/i?q=connect&shape=fill&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=5',
  'Case de otimização do RH com IA.','RH',
  'Processos lentos e manuais.','<p>Contexto inicial do case CPTO Connect.</p>',
  'Automação de triagens e rotinas.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Economia e velocidade em contratação.','<p>Resultados consolidados em redução de custo e prazo.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"R$ 2.500","label":"Economia Gerada"},{"value":"31 dias","label":"Tempo para 1º Resultado"}]'::jsonb
),
(
  'lacqua','Agência L''Acqua','Marketing',true,6,
  'Agência L''Acqua: Automação de Atendimento e Gestão',
  'Como uma agência com 12 anos de mercado transformou gargalos operacionais em processos fluídos e automáticos.',
  'https://img.usecurling.com/i?q=lacqua&shape=outline&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=6',
  'Case de eficiência operacional em agência.','Marketing',
  'Demandas crescendo acima da capacidade.','<p>Contexto inicial do case L''Acqua.</p>',
  'Estruturação e automação do fluxo.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Maior eficiência com menos esforço manual.','<p>Resultados consolidados com processos mais previsíveis.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"+60%","label":"Eficiência Operacional"},{"value":"100%","label":"Demandas Automatizadas"}]'::jsonb
),
(
  'casa-em-7','Casa em 7','Imobiliário',true,7,
  'Casa em 7: Plataforma criada em 3,5 meses e 90% de economia',
  'De 20 meses de frustração com desenvolvedores a uma plataforma robusta criada em tempo recorde com redução de custos.',
  'https://img.usecurling.com/i?q=casa&shape=fill&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=female&seed=7',
  'Case de desenvolvimento com IA.','Imobiliário',
  'Projeto travado por meses sem tração.','<p>Contexto inicial do case Casa em 7.</p>',
  'Execução com método e IA aplicada.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Entrega mais rápida e com menor custo.','<p>Resultados consolidados com economia significativa.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"90%","label":"Economia Gerada"},{"value":"10x menor investimento","label":"Redução de Custo"}]'::jsonb
),
(
  'dexi','Dexi Digital','Marketing',true,8,
  'Dexi Digital: R$ 1,7 milhão em pipeline mapeado com IA',
  'Como a Dexi Digital utilizou a inteligência artificial para escalar sua geração de leads B2B rapidamente.',
  'https://img.usecurling.com/i?q=dexi&shape=outline&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=8',
  'Case de crescimento em geração de demanda.','Marketing',
  'Crescimento de pipeline inconsistente.','<p>Contexto inicial do case Dexi.</p>',
  'Processo comercial orientado por IA.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Pipeline previsível e escalável.','<p>Resultados consolidados em geração de leads.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"R$ 1,7 milhão","label":"Gasoduto Gerado"},{"value":"1.230","label":"Leads Processados"}]'::jsonb
),
(
  'amsf','AMSF Advocacia','Jurídico',true,9,
  'AMSF Advocacia: CRM personalizado e pré-vendas otimizadas',
  'Como a AMSF Advocacia utilizou a mentoria para otimizar suas pré-vendas e customizar seu CRM jurídico.',
  'https://img.usecurling.com/i?q=advocacia&shape=outline&color=solid-black',
  'https://img.usecurling.com/ppl/thumbnail?gender=male&seed=9',
  'Case de eficiência comercial no jurídico.','Jurídico',
  'Pré-vendas sem padronização.','<p>Contexto inicial do case AMSF.</p>',
  'CRM customizado com apoio de IA.','<p>Implementação guiada com acompanhamento do time AV.</p>',
  'Mais previsibilidade e controle comercial.','<p>Resultados consolidados no processo de pré-vendas.</p>',
  null,null,null,null,null,null,
  'Sua agência vai ser o próximo case?','Aplique para a Mentoria Agência de Valor e estruture sua agência para os R$100k todo mês.','Aplicar agora','#',
  '[{"value":"Tempo Otimizado","label":"Pré-vendas"},{"value":"100%","label":"CRM Personalizado"}]'::jsonb
)
on conflict (slug) do update
set
  agency_name = excluded.agency_name,
  segment = excluded.segment,
  published = excluded.published,
  sort_order = excluded.sort_order,
  title = excluded.title,
  description = excluded.description,
  logo_url = excluded.logo_url,
  avatar_url = excluded.avatar_url,
  subtitle = excluded.subtitle,
  badge_label = excluded.badge_label,
  challenge_heading = excluded.challenge_heading,
  challenge_content = excluded.challenge_content,
  solution_heading = excluded.solution_heading,
  solution_content = excluded.solution_content,
  results_heading = excluded.results_heading,
  results_content = excluded.results_content,
  metrics = excluded.metrics,
  final_cta_heading = excluded.final_cta_heading,
  final_cta_body = excluded.final_cta_body,
  final_cta_label = excluded.final_cta_label,
  final_cta_url = excluded.final_cta_url;
